package Projeto.controller.Music;

public enum Sounds {
    GAME_SOUNDTRACK, GAME_SOUNDTRACK2,GAME_SOUNDTRACK3, GAMEOVER, VICTORY, MENU_SOUNDTRACK, SELECT, HIT,
    HP, HALF_MONEY ,DOUBLE_MONEY,NEW_LVL,COIN,INVULNERABLE;
}